export const applicantsHeader = [
  {
    id_: 1,
    title: " ",
    flex: "0.5",
    justifyContent: "flex-start",
    color: "red",
  },
  {
    id_: 2,
    title: "Candidate",
    flex: "2",
    color: "green",
    justifyContent: "flex-start",
  },
  {
    id_: 3,
    title: "Job Match",
    flex: "1",
    color: "blue",
    justifyContent: "flex-start",
  },
  {
    id_: 4,
    title: "Applied Date",
    flex: "1",
    color: "yellow",
    justifyContent: "flex-start",
  },
  {
    id_: 5,
    title: "Source",
    flex: "1",
    color: "orange",
    justifyContent: "flex-start",
  },
  {
    id_: 6,
    title: "Details",
    flex: "1",
    color: "white",
    justifyContent: "flex-start",
  },
  {
    id_: 7,
    title: "Actions",
    flex: "1",
    color: "purple",
    justifyContent: "center",
  },
];
