export const applicantInfo = [
  // {
  //   id_: 1,
  //   personalInfo: {
  //     name: "Abuzar Rahim",
  //     location: "San Francisco Bay Area",
  //     currentPosition: "Staff Engineer",
  //     company: "Ternoa",
  //   },
  //   jobMatch: {
  //     priority: "High",
  //   },
  //   AppliedDate: {
  //     AppliedDate: "Jan 17,2109",
  //   },
  //   source: {
  //     source: "Job Site",
  //   },
  // },
  {
    id_: 2,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "High",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 3,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 4,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "low",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 5,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 6,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Enf",
    company: "Ternsoa",
    priority: "low",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 7,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 8,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Enf",
    company: "Ternndnndnnn nnn nnn nnn noa",
    priority: "low",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 9,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 10,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Enf",
    company: "Ternoa",
    priority: "low",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 11,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 12,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Enf",
    company: "Ternnoa",
    priority: "low",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  {
    id_: 13,
    name: "Abuzar Rahim",
    location: "San Francisco Bay Area",
    currentPosition: "Staff Engineer",
    company: "Ternoa",
    priority: "high",
    date: "Jan 17,2109",
    source: "Job Site",
  },
  // {
  //   index: 1,
  //   name: "Abuzar Rahim",
  //   location: "San Francisco Bay Area",
  //   currentPosition: "Staff Engineer",
  //   company: "Ternoa",
  //   priority: "high",
  //   date: "Jan 17,2109",
  //   source: "Job Site",
  // },
  // {
  //   index: 1,
  //   name: "Abuzar Rahim",
  //   location: "San Francisco Bay Area",
  //   currentPosition: "Staff Engineer",
  //   company: "Ternoa",
  //   priority: "high",
  //   date: "Jan 17,2109",
  //   source: "Job Site",
  // },
  // {
  //   index: 2,
  //   name: "Abuzar Rahim",
  //   location: "San Francisco Bay Area",
  //   currentPosition: "Staff Engineer",
  //   company: "Ternoa",
  //   priority: "low",
  //   date: "Jan 17,2109",
  //   source: "Job Site",
  // },
  // {
  //   index: 3,
  //   name: "Abuzar Rahim",
  //   location: "San Francisco Bay Area",
  //   currentPosition: "Staff Engineer",
  //   company: "Ternoa",
  //   priority: "High",
  //   date: "Jan 17,2109",
  //   source: "Job Site",
  // },
  //  {
  //   index: 4,
  //   name: "Abuzar Rahim",
  //   location: "San Francisco Bay Area",
  //   currentPosition: "Staff Engineer",
  //   company: "Ternoa",
  //   priority: "High",
  //   date: "Jan 17,2109",
  //   source: "Job Site",
  // },
];
